version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine
    ports:
      - "6379:6379"

  web:
    restart: always
    build: ./library/
    image: web
    command: python ./library/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
    depends_on:
      db:
        condition: service_healthy

  migration:
    image: web
    command: python ./library/manage.py migrate --noinput
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy

  celery:
    image: web
    working_dir: /code/library
    command: celery -A library worker -l INFO
    volumes:
      - .:/code
    depends_on:
      redis:
        condition: service_started


